dist: xenial
language: python
python:
  - "3.7"
services:
  - docker
jobs:
  include:

    - stage: Unit Testing
      install:
        - pip install -r requirements/prod.txt
        - pip install -r requirements/dev.txt
      script:
        - python -m pytest -vv --cov=transport/ tests/unit

    - stage: Integration Testing
      install:
        - docker build . -t ftu
        - docker run -d -p 5000:5000 --env ftu_fake_it="true" ftu
        - pip install -r requirements/prod.txt
        - pip install -r requirements/dev.txt
      script:
        - python -m pytest tests/integration

    - stage: Selenium Testing
      install:
        - docker build . -t ftu
        - docker network create grid
        - docker run -d -p 5000:5000 --env ftu_fake_it="true" --network="grid" --name test_server ftu
        - docker run -d -p 4444:4444 -p 5900:5900 -v /dev/shm:/dev/shm --network="grid" selenium/standalone-chrome-debug
        - pip install -r requirements/prod.txt
        - pip install -r requirements/dev.txt
      script:
        - behave tests/ui/
