dist: xenial
language: python
python:
  - "3.7"
install:
  - pip install -r requirements/prod.txt
  - pip install -r requirements/dev.txt
script:
  - python -m pytest -vv --durations=0 --cov=transport/
