name: Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/prod.txt
          pip install -r requirements/dev.txt
      - name: Isort
        run: |
          isort --check-only transport tests
      - name: Black
        run: |
          black --check transport tests
      - name: Flake8
        run: |
          flake8 transport tests
      - name: Unit tests
        run: |
          python -m pytest -vv --cov=transport/ tests/unit
      - name: Start system under test
        run: |
          docker-compose up -d
      - name: Integration tests
        run: |
          python -m pytest tests/integration
      - name: Selenium tests
        run: |
          behave tests/ui/
