name: Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/prod.txt
          pip install -r requirements/dev.txt
      - name: isort
        run: |
          isort --check-only transport tests
      - name: black
        run: |
          black --check transport tests
      - name: flake8
        run: |
          flake8 transport tests
      - name: Unit tests
        run: |
          python -m pytest -vv --cov=transport/ tests/unit
      - name: Build docker container
        run: |
          docker build . -t local
      - name: Run docker container
        run: |
          docker network create grid
          docker run -d -p 5000:5000 --env ftu_fake_it="true" --network="grid" --name test_server local
      - name: Integration tests
        run: |
          python -m pytest tests/integration
      - name: Selenium tests
        run: |
          docker run -d -p 4444:4444 -p 5900:5900 -v /dev/shm:/dev/shm --network="grid" selenium/standalone-chrome-debug
          sleep 30
          behave tests/ui/
