# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
           pip install -r requirements/prod.txt
          pip install -r requirements/dev.txt
      - name: Unit tests
        run: |
          python -m pytest -vv --cov=transport/ tests/unit
      - name: Build docker container
        run: |
          docker build . -t local
      - name: Run docker container
        run: |
          docker network create grid
          docker run -d -p 5000:5000 --env ftu_fake_it="true" --network="grid" --name test_server local
      - name: Integration tests
        run: |
          python -m pytest tests/integration
      - name: Selenium tests
        run: |
          docker run -d -p 4444:4444 -p 5900:5900 -v /dev/shm:/dev/shm --network="grid" selenium/standalone-chrome-debug
          sleep 30
          behave tests/ui/
